services:
  postgres:
    image: postgres:16.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_SCRIPTS: /var/lib/postgresql/data/init-db.sql
    volumes:
      - postgres:/data/postgres
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - app
    restart: unless-stopped

networks:
  app:
    driver: bridge

volumes:
  scripts:
  postgres: